AI_API/AI_API/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ml_model.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AI_API/ml_model/urls.py
from django.urls import path

from . import views

app_name = 'ml_model'

urlpatterns = [
    path('', views.index, name='home'),
    path('results/', views.results_page, name='results'),
    path('about/', views.about_page, name='about'),
    path('about_model/', views.about_model_page, name='about_model'),
]

AI_API/ml_model/models.py
from django.db import models
from .model.model import predict_image
import os


class Image(models.Model):
    class_choices = [
        (0, 'airplane'),
        (1, 'automobile'),
        (2, 'bird'),
        (3, 'cat'),
        (4, 'deer'),
        (5, 'dog'),
        (6, 'frog'),
        (7, 'horse'),
        (8, 'ship'),
        (9, 'truck'),
    ]
    image_class = models.IntegerField(choices=class_choices)
    image_predicted_class = models.IntegerField(choices=class_choices)
    image = models.ImageField(upload_to="img")

    def __str__(self):
        return f"{self.get_image_class_display()} - {self.id}"

    def save(self, *args, **kwargs):
        copied_image = self.image
        self.image_predicted_class = predict_image(copied_image)
        super().save(*args, **kwargs)

AI_API/ml_model/views.py
from django.shortcuts import render, redirect
from .form import ImageForm
from .models import Image


def index(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            latest_image = Image.objects.latest('id')
            return render(request, "index.html",
                          {"form": form, "latest_image": latest_image, 'image_class_choices': Image.class_choices})
    else:
        form = ImageForm()
    img = Image.objects.all()
    return render(request, "index.html", {"img": img, "form": form, 'image_class_choices': Image.class_choices})


def results_page(request):
    results = Image.objects.all().order_by('-id')
    return render(request, 'results.html', {'img': results})


def about_page(request):
    return render(request, 'about.html')


def about_model_page(request):
    return render(request, 'about_model.html')

AI_API/ml_model/templates/about.html
{% extends 'base.html' %}
{% block title %}Page Title{% endblock %}
{% block content %}
{% load static %}
<main>

    <div class="person-info-container block-info">
        <div class="image-container">
            <img src="{% static 'images/photo1.jpg' %}" alt="Person 2">
        </div>
        <div class="text-info block-info">
            <p>Я вирішив обрати кар'єру в галузі IT через переконання в тому, що це майбутнє, де технології постійно розвиваються. Ще зі шкільних років я відчував зацікавленість до технічних спеціальностей, і вірю, що в цій галузі можна знайти безмежні можливості для кар'єрного зростання та самореалізації.</p>
        </div>
    </div>


    <div class="person-info-container block-info">
        <div class="image-container">
            <img src="{% static 'images/photo2.jpg' %}" alt="Person 2">
        </div>
        <div class="text-info block-info">
            <p>Я вибрала галузь IT, через те що цікавлюсь новими технологіями. Я паралельно вчусь на веб-дизайнера в університеті, тобто в напрямку frontend розробки. Я захотіла знати не тільки як працює сайт ззовні, але також як він працює зсередини, тому пішла на backend розробку.</p>
        </div>
    </div>

    <div class="person-info-container block-info">
        <div class="image-container">
            <img src="{% static 'images/photo3.jpg' %}" alt="Person 3">
        </div>
        <div class="text-info">
            <p>Я вирішив зробити кар'єру в it, а також пов'язати її з вивченням Python з простої причини - це дуже корисна мова програмування. Вона дуже популярна, легка для вивчення і використання, і відкриває багато можливостей для знаходження роботи та створення цікавих проектів.
</p>
        </div>
    </div>

    <div class="person-info-container block-info">
        <div class="image-container">
            <img src="{% static 'images/photo4.jpg' %}" alt="Person 4">
        </div>
        <div class="text-info">
            <p>Для мене кар’єра в галузі IT це сфера діяльності в якій я вже давно прагнув розвиватися. Програмування на мові Python дало мені поштовх для отримання IT освіти і здобуття нових вершин. Програмування це процес від якого отримуєш максимум задоволення коли відбувається магія перетворення коду в необхідний продукт.</p>
        </div>
    </div>

    <div class="person-info-container block-info">
        <div class="image-container">
            <img src="{% static 'images/photo5.jpg' %}" alt="Person 5">
        </div>
        <div class="text-info">
            <p>Для мене робота в сфері IT - це не лише професія, це спосіб мислення, що став важливою частиною мого життя. Ще з дитинства я цікавився комп'ютерами та усією сферою технологій загалом, але коли я вперше створив свою програму на Python, відчув, що знайшов своє покликання. Відтоді кожен новий крок у світі IT - це  можливість займатися улюбленою справою.</p>
        </div>
    </div>
</main>
{% endblock %}

AI_API/ml_model/templates/base.html
  {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CatCaptures{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href='{% static 'css/styles.css' %}' rel='stylesheet'></link>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" alt="Логотип" width="50" height="50">
        </a>
        <a class="navbar-brand">CatCaptures</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <!-- Вкладка "Головна" -->
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'ml_model:home' %}">Головна</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="{% url 'ml_model:about' %}">Про нас</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/about_model/' %}active{% endif %}" href="{% url 'ml_model:about_model' %}">Про модель</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/results/' %}active{% endif %}" href="{% url 'ml_model:results' %}">Результати</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

AI_API/ml_model/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
       <div class="block" style="background-color: #2e323c; border: none;"> <!-- Змінено фон і видалено обводку -->
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
    <label for="id_image" class="custom-file-upload">
        <span id="file-name-placeholder">Виберіть файл</span> <!-- Початковий текст -->
        <input type="file" id="id_image" name="image" accept="image/*" style="display: none;" onchange="updateFileName(this)"> <!-- Подія onchange спрацьовує при виборі файлу -->
    </label>
</div>


        <div class="form-group">
            <label for="id_class">Виберіть клас:</label>
            <select class="form-control" id="id_class" name="image_class" required>
                {% for value, label in image_class_choices %}
                    <option value="{{ value }}">{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Завантажити</button>
    </form>
</div>

        {% if latest_image %}
        <div class="block mt-4" style="background-color: #2e323c; border: none;"> <!-- Змінено фон і видалено обводку -->
            <div class="row">

                <div class="col-md-6">
                    <img src="{{ latest_image.image.url }}" alt="Uploaded Image" class="img-fluid">
                </div>

                <div class="col-md-6">
                    <p><strong>Предбачений клас:</strong></p>
                    <p>{{ latest_image.get_image_predicted_class_display }}</p>
                    <p><strong>Справжній клас:</strong></p>
                    <p>{{ latest_image.get_image_class_display }}</p>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

AI_API/ml_model/templates/results.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% for image in img%}
                <div class="block">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="{{ image.image.url }}" alt="Uploaded Image" class="img-fluid">
                        </div>
                        <div class="col-md-6">
                            <div class="predicted-class">
                                <p><strong>Предбачений клас:</strong></p>
                                <p>{{ image.get_image_predicted_class_display }}</p>
                            </div>
                            <div class="true-class">
                                <p><strong>Справжній клас:</strong></p>
                                <p>{{ image.get_image_predicted_class_display }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}